algoritmo "primeiro"
// Função :
// Autor : Talita
// Data : 30/08/2021
// Seção de Declarações 
var

   MSG: caractere
   
// Seção de preenchimento dos espaços (agregação de valor)

inicio

MSG<-"Ola, Mundo!"
escreval(MSG)
escreva ("Ufa, me livrei da maldição! Espero que não seja tarde demais!")

 // Há uma maldição que faz com que programadores nunca sejam bons o bastante se seu primeiro código não for "Olá Mundo"
// Seção de Comandos
 
fimalgoritmo
